#!/bin/bash
path=`pwd`
sysctlpath="/lib/systemd/system/"

if [ -z $1 ]; then
	echo use with setup_systemctl install/uninstall
	exit 1
fi

if [ $1 = "install" ]; then
cat > $sysctlpath/evoheat_control.service << EOF
[Unit]
Description=HeatPumpWater_Control
After=network-online.target

[Service]
Type=simple
ExecStart=${path}/control.sh

[Install]
WantedBy=multi-user.target
EOF
cat > $sysctlpath/evoheat_status.service << EOF
[Unit]
Description=HeatPumpWater_Status
After=network-online.target

[Service]
Type=simple
ExecStart=${path}/status.sh

[Install]
WantedBy=multi-user.target
EOF

systemctl enable evoheat_control.service
systemctl enable evoheat_status.service
systemctl start evoheat_control.service
systemctl start evoheat_status.service

elif [ $1 = "uninstall" ]; then
	systemctl stop evoheat_control.service
	systemctl stop evoheat_status.service
	systemctl disable evoheat_control.service
	systemctl disable evoheat_status.service
	rm -f $sysctlpath/evoheat_control.service
	rm -f $sysctlpath/evoheat_status.service
	

fi
